<script setup>
import { reactive, ref, watch } from 'vue';
const props=defineProps({set:Object,number:Number,unit:String,metricType:String}); const emit=defineEmits(['save','remove']);
const form=reactive({set_number:props.number,set_type:'working',weight:null,weight_unit:props.unit,repetitions:null,duration_seconds:null,rir:null,technique_rating:null,rest_seconds_actual:null,completed:true,notes:null});
const details=ref(false);
watch(()=>props.set,(set)=>{if(set)Object.assign(form,set);},{immediate:true}); watch(()=>props.number,(number)=>{if(!props.set)form.set_number=number;});
</script>
<template>
  <tr :class="{'set-warmup':form.set_type==='warmup'}"><td><span :title="form.set_type">{{ form.set_number }}</span></td><td><select v-model="form.set_type" class="form-select" title="Tipo de serie"><option value="warmup">Cal.</option><option value="working">Efectiva</option><option value="backoff">Descarga</option><option value="drop">Drop</option></select></td><td v-if="metricType!=='duration'&&metricType!=='reps_only'&&metricType!=='bodyweight_reps'"><input v-model.number="form.weight" class="form-control" type="number" min="0" step=".25" placeholder="0"/></td><td v-if="metricType!=='duration'&&metricType!=='weight_duration'"><input v-model.number="form.repetitions" class="form-control" type="number" min="0" placeholder="0"/></td><td v-else><input v-model.number="form.duration_seconds" class="form-control" type="number" min="0" placeholder="seg"/></td><td><input v-model.number="form.rir" class="form-control" type="number" min="0" max="5" placeholder="-"/></td><td><button class="icon-button compact set-complete" title="Guardar serie" @click="$emit('save',{...form})"><i class="fa-solid fa-check"/></button></td><td><div class="d-flex gap-1"><button class="icon-button compact" title="Tecnica, descanso y notas" @click="details=!details"><i class="fa-solid fa-sliders"/></button><button v-if="set" class="icon-button compact" title="Eliminar serie" @click="$emit('remove',set.id)"><i class="fa-solid fa-trash"/></button></div></td></tr>
  <tr v-if="details" class="set-details"><td colspan="7"><div class="field-grid"><div><label class="form-label">Unidad</label><select v-model="form.weight_unit" class="form-select"><option value="kg">kg</option><option value="lb">lb</option></select></div><div><label class="form-label">Tecnica (1-5)</label><input v-model.number="form.technique_rating" class="form-control" type="number" min="1" max="5" placeholder="Opcional"/></div><div><label class="form-label">Descanso real (s)</label><input v-model.number="form.rest_seconds_actual" class="form-control" type="number" min="0" max="3600" placeholder="Opcional"/></div><div class="d-flex align-items-end"><label class="form-check mb-2"><input v-model="form.completed" class="form-check-input" type="checkbox"/> Serie completada</label></div><div class="grid-column-full"><label class="form-label">Notas</label><input v-model="form.notes" class="form-control" maxlength="1000" placeholder="Ejecucion, tempo o contexto"/></div></div></td></tr>
</template>
