<script setup>
import { computed, onMounted, ref } from 'vue';
import { useRoute } from 'vue-router';
import api from '../api/client';
import LoadingSkeleton from '../components/common/LoadingSkeleton.vue';
import { useNotificationStore } from '../stores/notifications';
import { errorMessage } from '../utils/errors';
const route=useRoute(); const notifications=useNotificationStore(); const session=ref(null); const loading=ref(true);
const statusLabels={completed:'Completado',partial:'Parcial',cancelled:'Cancelado',in_progress:'En curso'};
const setTypeLabels={warmup:'Calentamiento',working:'Efectiva',backoff:'Descarga',drop:'Drop set'};
const reasonLabels={equipment_busy:'Equipo ocupado',equipment_unavailable:'Equipo no disponible',discomfort:'Molestia',personal_preference:'Preferencia personal',other:'Otro'};
const effectiveSets=computed(()=>session.value?.exercises.flatMap(x=>x.sets).filter(s=>s.completed&&s.set_type!=='warmup')||[]); const records=computed(()=>effectiveSets.value.filter(s=>s.is_personal_record));
function duration(seconds){const total=Math.max(0,Math.round(Number(seconds)||0));const hours=Math.floor(total/3600);const minutes=Math.floor((total%3600)/60);const secs=total%60;return hours?`${hours}:${String(minutes).padStart(2,'0')}:${String(secs).padStart(2,'0')}`:`${minutes}:${String(secs).padStart(2,'0')}`;}
async function load(){try{session.value=(await api.get(`/workouts/${route.params.id}`)).data.data;}catch(e){notifications.push(errorMessage(e),'error');}finally{loading.value=false;}}
onMounted(load);
</script>
<template><div><RouterLink class="btn btn-outline-light mb-3" :to="{name:'history'}"><i class="fa-solid fa-arrow-left"/>Historial</RouterLink><LoadingSkeleton v-if="loading"/><template v-else-if="session"><header class="page-header"><div><div class="eyebrow">{{ new Date(session.started_at).toLocaleDateString('es-GT',{dateStyle:'long'}) }}</div><h1>{{ session.name }}</h1><p>{{ session.status==='completed'?'Entrenamiento completado':session.status==='partial'?'Entrenamiento parcial':'Sesion '+session.status }}</p></div><span class="badge-soft" :class="session.status==='completed'?'green':'yellow'">{{ statusLabels[session.status]||session.status }}</span></header>
  <section class="grid stats-grid"><article class="stat-card"><span class="stat-icon"><i class="fa-solid fa-stopwatch"/></span><strong>{{ duration(session.duration_seconds) }}</strong><small>Duracion</small></article><article class="stat-card"><span class="stat-icon"><i class="fa-solid fa-list-check"/></span><strong>{{ effectiveSets.length }}</strong><small>Series efectivas</small></article><article class="stat-card"><span class="stat-icon"><i class="fa-solid fa-weight-hanging"/></span><strong>{{ Number(session.total_volume||0).toFixed(0) }}</strong><small>Volumen</small></article><article class="stat-card streak"><span class="stat-icon"><i class="fa-solid fa-trophy"/></span><strong>{{ records.length }}</strong><small>Records</small></article><article class="stat-card energy"><span class="stat-icon"><i class="fa-solid fa-bolt"/></span><strong>+{{ session.xp_earned }}</strong><small>XP ganada</small></article><article class="stat-card power"><span class="stat-icon"><i class="fa-solid fa-fire"/></span><strong>+{{ session.power_earned }}</strong><small>Poder ganado</small></article><article class="stat-card"><span class="stat-icon"><i class="fa-solid fa-bullseye"/></span><strong>{{ session.weekly_progress?.completed??0 }}/{{ session.weekly_progress?.goal??4 }}</strong><small>Progreso semanal</small></article><article class="stat-card streak"><span class="stat-icon"><i class="fa-solid fa-calendar-check"/></span><strong>{{ session.current_weekly_streak??0 }}</strong><small>Semanas de racha</small></article></section>
  <section v-if="session.improvements?.length" class="surface panel section-block"><div class="section-heading"><div><h2>Ejercicios mejorados</h2><p>Comparaciones contra la exposicion anterior guardada al iniciar.</p></div></div><div class="recommendation-list"><article v-for="item in session.improvements" :key="item.exercise" class="recommendation-row"><strong>{{ item.exercise }}</strong><p class="small text-secondary mb-0 mt-1">{{ item.message }}</p></article></div></section>
  <section class="section-block"><div class="section-heading"><div><h2>Ejercicios realizados</h2><p>Las alternativas conservan el ejercicio planificado y el realizado.</p></div></div><div class="exercise-list"><article v-for="item in session.exercises" :key="item.id" class="day-card"><header><div><h3>{{ item.performed_exercise.name }}</h3><small v-if="item.was_substituted"><i class="fa-solid fa-shuffle me-1"/>En lugar de {{ item.planned_exercise.name }} · {{ reasonLabels[item.substitution_reason]||item.substitution_reason }}</small><small v-else>{{ item.performed_exercise.muscle_groups?.map(g=>g.name).join(', ') }}</small></div><span v-if="item.sets.some(s=>s.is_personal_record)" class="badge-soft yellow"><i class="fa-solid fa-trophy"/>Record</span></header><div class="table-responsive mt-3"><table class="table table-dark table-sm align-middle mb-0"><thead><tr><th>#</th><th>Tipo</th><th>Peso</th><th>Reps/seg</th><th>RIR</th><th>Tecnica</th><th>Descanso</th><th>Notas</th></tr></thead><tbody><tr v-for="set in item.sets" :key="set.id"><td>{{ set.set_number }}</td><td>{{ setTypeLabels[set.set_type]||set.set_type }}</td><td>{{ set.weight??'-' }} {{ set.weight_unit||'' }}</td><td>{{ set.repetitions??set.duration_seconds??'-' }}</td><td>{{ set.rir??'-' }}</td><td>{{ set.technique_rating??'-' }}</td><td>{{ set.rest_seconds_actual??'-' }} s</td><td>{{ set.notes||'-' }}</td></tr></tbody></table></div><p v-if="item.notes" class="small text-secondary mt-3 mb-0">{{ item.notes }}</p><div v-if="item.recommendation" class="recommendation-accent mt-3"><small class="text-secondary d-block">Recomendacion usada al iniciar</small><p class="small mb-0">{{ item.recommendation.reason }}</p></div></article></div></section>
  <section v-if="session.sleep_hours||session.energy_level||session.motivation_level||session.discomfort_notes||session.is_atypical||session.notes" class="surface panel section-block"><div class="section-heading"><h2>Contexto de la sesion</h2></div><div class="field-grid"><div><small class="text-secondary d-block">Sueno</small><strong>{{ session.sleep_hours??'-' }} h</strong></div><div><small class="text-secondary d-block">Energia</small><strong>{{ session.energy_level??'-' }}/5</strong></div><div><small class="text-secondary d-block">Motivacion</small><strong>{{ session.motivation_level??'-' }}/5</strong></div><div><small class="text-secondary d-block">Dificultad</small><strong>{{ session.session_difficulty??'-' }}/5</strong></div><div><small class="text-secondary d-block">Satisfaccion</small><strong>{{ session.session_satisfaction??'-' }}/5</strong></div><div><small class="text-secondary d-block">Sesion atipica</small><strong>{{ session.is_atypical?'Si':'No' }}</strong></div></div><p v-if="session.discomfort_notes" class="mt-3 mb-0 text-secondary"><strong>Molestias o comentarios:</strong> {{ session.discomfort_notes }}</p><p v-if="session.atypical_reason" class="mt-2 mb-0 text-secondary"><strong>Motivo atipico:</strong> {{ session.atypical_reason }}</p><p v-if="session.notes" class="mt-2 mb-0 text-secondary">{{ session.notes }}</p></section>
</template></div></template>
