<script setup>
import { onMounted, reactive, ref } from 'vue';
import { useRouter } from 'vue-router';
import api from '../api/client';
import LoadingSkeleton from '../components/common/LoadingSkeleton.vue';
import { useAuthStore } from '../stores/auth';
import { useNotificationStore } from '../stores/notifications';
import { errorMessage } from '../utils/errors';
const router=useRouter(); const auth=useAuthStore(); const notifications=useNotificationStore(); const loading=ref(true); const saving=ref(false); const showPasswords=ref(false); const user=ref({}); const form=reactive({}); const password=reactive({current_password:'',password:'',password_confirmation:''});
async function load(){try{const response=(await api.get('/profile')).data;user.value=response.user;Object.assign(form,response.profile);}catch(e){notifications.push(errorMessage(e),'error');}finally{loading.value=false;}}
async function save(){saving.value=true;try{const payload={age:form.age,height_cm:form.height_cm,preferred_body_weight_unit:form.preferred_body_weight_unit,objective:form.objective,weekly_workout_goal:form.weekly_workout_goal,target_session_minutes:form.target_session_minutes,maximum_session_minutes:form.maximum_session_minutes,protein_goal_min_grams:form.protein_goal_min_grams,protein_goal_max_grams:form.protein_goal_max_grams,sleep_goal_hours:form.sleep_goal_hours,notes:form.notes};Object.assign(form,(await api.put('/profile',payload)).data.profile);notifications.push('Perfil actualizado.');}catch(e){notifications.push(errorMessage(e),'error');}finally{saving.value=false;}}
async function changePassword(){try{await api.put('/profile/password',password);Object.assign(password,{current_password:'',password:'',password_confirmation:''});notifications.push('Contrasena actualizada.');}catch(e){notifications.push(errorMessage(e),'error');}}
async function logout(){await auth.logout();router.push({name:'login'});}
onMounted(load);
</script>
<template><div><header class="page-header"><div><div class="eyebrow">Cuenta personal</div><h1>Mi perfil</h1><p>Metas y referencias de la fase actual.</p></div></header><LoadingSkeleton v-if="loading"/><template v-else><section class="surface panel"><div class="d-flex align-items-center gap-3 mb-4"><span class="user-avatar" style="width:54px;height:54px;font-size:20px">{{ user.name?.slice(0,1) }}</span><div><strong class="d-block fs-5">{{ user.name }}</strong><small class="text-secondary">{{ user.email }}</small></div></div><form class="field-grid" @submit.prevent="save"><div><label class="form-label">Edad</label><input v-model.number="form.age" class="form-control" type="number" min="13" max="120"/></div><div><label class="form-label">Estatura (cm)</label><input v-model.number="form.height_cm" class="form-control" type="number" min="80" max="250" step=".1"/></div><div><label class="form-label">Objetivo</label><select v-model="form.objective" class="form-select"><option value="body_recomposition">Recomposicion corporal</option><option value="muscle_gain">Ganancia muscular</option><option value="fat_loss">Perdida de grasa</option><option value="strength">Fuerza</option><option value="general_fitness">Condicion general</option></select></div><div><label class="form-label">Unidad preferida</label><select v-model="form.preferred_body_weight_unit" class="form-select"><option value="lb">Libras</option><option value="kg">Kilogramos</option></select></div><div><label class="form-label">Meta semanal</label><input v-model.number="form.weekly_workout_goal" class="form-control" type="number" min="1" max="7"/></div><div><label class="form-label">Duracion objetivo (min)</label><input v-model.number="form.target_session_minutes" class="form-control" type="number" min="15" max="180"/></div><div><label class="form-label">Duracion maxima (min)</label><input v-model.number="form.maximum_session_minutes" class="form-control" type="number" min="15" max="240"/></div><div><label class="form-label">Sueno orientativo (h)</label><input v-model.number="form.sleep_goal_hours" class="form-control" type="number" min="0" max="16" step=".5"/></div><div><label class="form-label">Proteina minima (g)</label><input v-model.number="form.protein_goal_min_grams" class="form-control" type="number" min="0" max="500"/></div><div><label class="form-label">Proteina maxima (g)</label><input v-model.number="form.protein_goal_max_grams" class="form-control" type="number" min="0" max="500"/></div><div class="grid-column-full"><label class="form-label">Notas</label><textarea v-model="form.notes" class="form-control" rows="4"/></div><div class="grid-column-full"><button class="btn btn-primary" :disabled="saving"><i class="fa-solid fa-floppy-disk"/>{{ saving?'Guardando...':'Guardar perfil' }}</button></div></form></section>
  <section class="surface panel section-block"><div class="section-heading"><div><h2>Mediciones actuales</h2><p>Se actualizan desde tu registro de progreso corporal.</p></div><RouterLink class="btn btn-outline-light btn-sm" :to="{name:'progress'}"><i class="fa-solid fa-chart-line"/>Ver progreso</RouterLink></div><div class="grid stats-grid"><article class="stat-card"><span class="stat-icon"><i class="fa-solid fa-weight-scale"/></span><strong>{{ form.current_body_weight_kg??'-' }}</strong><small>Peso actual (kg)</small></article><article class="stat-card"><span class="stat-icon"><i class="fa-solid fa-ruler"/></span><strong>{{ form.current_waist_cm??'-' }}</strong><small>Cintura actual (cm)</small></article></div></section>
  <section class="surface panel section-block"><div class="section-heading"><div><h2>Cambiar contrasena</h2><p>Usa al menos ocho caracteres.</p></div><button class="icon-button compact" :title="showPasswords?'Ocultar contrasenas':'Mostrar contrasenas'" @click="showPasswords=!showPasswords"><i class="fa-solid" :class="showPasswords?'fa-eye-slash':'fa-eye'"/></button></div><form class="field-grid" @submit.prevent="changePassword"><div><label class="form-label">Contrasena actual</label><input v-model="password.current_password" class="form-control" :type="showPasswords?'text':'password'" required/></div><div><label class="form-label">Nueva contrasena</label><input v-model="password.password" class="form-control" :type="showPasswords?'text':'password'" required minlength="8"/></div><div><label class="form-label">Confirmar contrasena</label><input v-model="password.password_confirmation" class="form-control" :type="showPasswords?'text':'password'" required/></div><div class="d-flex align-items-end"><button class="btn btn-outline-light w-100"><i class="fa-solid fa-key"/>Actualizar</button></div></form></section>
  <section class="section-block"><button class="btn btn-danger-soft" @click="logout"><i class="fa-solid fa-right-from-bracket"/>Cerrar sesion</button><p class="small text-secondary mt-3">Golden Path es una herramienta personal de registro y motivacion. No sustituye la evaluacion de un profesional de salud o entrenamiento.</p></section>
</template></div></template>
