<script setup>
import { computed, onMounted, reactive, ref } from 'vue';
import api from '../api/client';
import { useRoute } from 'vue-router';
import ActivityCalendar from '../components/progress/ActivityCalendar.vue';
import LineChart from '../components/progress/LineChart.vue';
import BaseModal from '../components/common/BaseModal.vue';
import EmptyState from '../components/common/EmptyState.vue';
import LoadingSkeleton from '../components/common/LoadingSkeleton.vue';
import { useNotificationStore } from '../stores/notifications';
import { errorMessage } from '../utils/errors';
const route=useRoute();
const notifications=useNotificationStore(); const loading=ref(true); const tab=ref('overview'); const overview=ref({}); const activity=ref([]); const body=ref({data:[],summary:{}}); const exercises=ref([]); const achievements=ref([]); const recommendations=ref([]); const selectedExercise=ref(null); const exerciseData=ref(null); const measurementOpen=ref(false); const editingMeasurement=ref(null); const measurement=reactive({recorded_on:new Date().toISOString().slice(0,10),body_weight_kg:null,waist_cm:null,notes:null}); const recommendationOpen=ref(false); const editingRecommendation=ref(null); const recommendationChange=reactive({suggested_weight:null,suggested_total_repetitions:null});
const bodyLabels=computed(()=>body.value.data.map(item=>item.recorded_on)); const bodyDatasets=computed(()=>[{label:'Peso (kg)',data:body.value.data.map(item=>item.body_weight_kg)},{label:'Cintura (cm)',data:body.value.data.map(item=>item.waist_cm)}]);
const exerciseLabels=computed(()=>exerciseData.value?.series.map(item=>item.date)||[]); const exerciseDatasets=computed(()=>[{label:'Peso maximo',data:exerciseData.value?.series.map(item=>item.max_weight)||[]},{label:'Repeticiones totales',data:exerciseData.value?.series.map(item=>item.total_repetitions)||[]},{label:'Volumen',data:exerciseData.value?.series.map(item=>item.volume)||[]},{label:'1RM estimado',data:exerciseData.value?.series.map(item=>item.estimated_one_rep_max)||[]}]);
async function load(){loading.value=true;try{const [a,b,c,d,e,f]=await Promise.all([api.get('/progress/overview'),api.get('/progress/activity-calendar'),api.get('/progress/body'),api.get('/progress/exercises'),api.get('/game/achievements'),api.get('/progression/recommendations',{params:{status:'pending'}})]);overview.value=a.data;activity.value=b.data.data;body.value=c.data;exercises.value=d.data.data;achievements.value=e.data.data;recommendations.value=f.data.data;if(exercises.value.length&&!selectedExercise.value){const requested=Number(route.query.exercise);selectedExercise.value=exercises.value.some(item=>item.id===requested)?requested:exercises.value[0].id;await loadExercise();}}catch(e){notifications.push(errorMessage(e),'error');}finally{loading.value=false;}}
async function loadExercise(){if(!selectedExercise.value)return;try{exerciseData.value=(await api.get(`/progress/exercises/${selectedExercise.value}`)).data;}catch(e){notifications.push(errorMessage(e),'error');}}
function openMeasurement(item=null){editingMeasurement.value=item;Object.assign(measurement,item?{recorded_on:item.recorded_on,body_weight_kg:item.body_weight_kg,waist_cm:item.waist_cm,notes:item.notes}:{recorded_on:new Date().toISOString().slice(0,10),body_weight_kg:null,waist_cm:null,notes:null});measurementOpen.value=true;}
async function saveMeasurement(){try{if(editingMeasurement.value)await api.put(`/body-measurements/${editingMeasurement.value.id}`,measurement);else await api.post('/body-measurements',measurement);measurementOpen.value=false;notifications.push(editingMeasurement.value?'Medicion actualizada.':'Medicion registrada.');await load();}catch(e){notifications.push(errorMessage(e),'error');}}
async function removeMeasurement(item){if(!confirm('Eliminar esta medicion?'))return;try{await api.delete(`/body-measurements/${item.id}`);notifications.push('Medicion eliminada.');await load();}catch(e){notifications.push(errorMessage(e),'error');}}
async function act(item,action){try{await api.post(`/progression/recommendations/${item.id}/${action}`);notifications.push(action==='accept'?'Recomendacion aceptada.':'Recomendacion ignorada.');await load();}catch(e){notifications.push(errorMessage(e),'error');}}
function openRecommendation(item){editingRecommendation.value=item;Object.assign(recommendationChange,{suggested_weight:item.suggested_weight,suggested_total_repetitions:item.suggested_total_repetitions});recommendationOpen.value=true;}
function trend(field){const values=body.value.data.map(item=>item[field]).filter(value=>value!=null).map(Number);if(values.length<2)return 'Sin tendencia';const delta=values.at(-1)-values.at(-2);return Math.abs(delta)<.05?'Estable':`${delta>0?'Sube':'Baja'} ${Math.abs(delta).toFixed(1)}`;}
async function modifyRecommendation(){try{await api.post(`/progression/recommendations/${editingRecommendation.value.id}/modify`,recommendationChange);recommendationOpen.value=false;notifications.push('Recomendacion modificada y aplicada.');await load();}catch(e){notifications.push(errorMessage(e),'error');}}
const change=(current,initial)=>current!=null&&initial!=null?(Number(current)-Number(initial)).toFixed(1):'-';
const recommendationLabels={calibrate:'Calibracion',increase_weight:'Aumentar peso',increase_repetitions:'Aumentar repeticiones',maintain:'Mantener',reduce_weight:'Reducir peso',increase_rest:'Aumentar descanso',possible_deload:'Posible descarga',manual_review:'Revision manual'};
const recommendationLabel=type=>recommendationLabels[type]||type;
const confidenceLabels={low:'Baja',medium:'Media',high:'Alta'};
const confidenceLabel=value=>confidenceLabels[value]||value;
onMounted(load);
</script>
<template><div><header class="page-header"><div><div class="eyebrow">Evidencia personal</div><h1>Progreso</h1><p>Cintura, rendimiento y adherencia cuentan mas que una sola cifra.</p></div><button class="btn btn-primary" @click="openMeasurement()"><i class="fa-solid fa-plus"/>Medicion</button></header>
  <div class="segmented-control mb-4"><button v-for="item in [['overview','Resumen'],['body','Cuerpo'],['exercise','Ejercicio'],['achievements','Logros']]" :key="item[0]" :class="{active:tab===item[0]}" @click="tab=item[0]">{{ item[1] }}</button></div><LoadingSkeleton v-if="loading"/><template v-else>
    <div v-if="tab==='overview'"><section class="grid stats-grid"><article class="stat-card"><span class="stat-icon"><i class="fa-solid fa-dumbbell"/></span><strong>{{ overview.completed_sessions||0 }}</strong><small>Sesiones en la fase</small></article><article class="stat-card"><span class="stat-icon"><i class="fa-solid fa-weight-scale"/></span><strong>{{ change(body.summary.current_weight,body.summary.initial_weight) }}</strong><small>Cambio de peso (kg)</small></article><article class="stat-card streak"><span class="stat-icon"><i class="fa-solid fa-ruler"/></span><strong>{{ change(body.summary.current_waist,body.summary.initial_waist) }}</strong><small>Cambio de cintura (cm)</small></article><article class="stat-card"><span class="stat-icon"><i class="fa-solid fa-trophy"/></span><strong>{{ overview.records?.length||0 }}</strong><small>Records activos</small></article></section><section class="surface panel section-block"><div class="section-heading"><div><h2>Actividad de las ultimas 16 semanas</h2><p>La racha se mide por semanas completas, no por dias consecutivos.</p></div></div><ActivityCalendar :items="activity"/></section><section class="section-block"><div class="section-heading"><div><h2>Recomendaciones</h2><p>Ningun cambio se aplica sin tu decision.</p></div></div><div v-if="recommendations.length" class="recommendation-list"><article v-for="item in recommendations" :key="item.id" class="recommendation-row"><div class="d-flex justify-content-between gap-2"><strong>{{ item.exercise.name }}</strong><span class="badge-soft blue">{{ confidenceLabel(item.confidence) }}</span></div><p class="small text-secondary my-2">{{ item.reason }}</p><div class="d-flex gap-2"><button class="btn btn-primary btn-sm" @click="act(item,'accept')"><i class="fa-solid fa-check"/>Aceptar</button><button class="btn btn-outline-light btn-sm" @click="openRecommendation(item)"><i class="fa-solid fa-pen"/>Modificar</button><button class="btn btn-outline-light btn-sm" @click="act(item,'ignore')">Ignorar</button></div></article></div><EmptyState v-else title="Sin decisiones pendientes" text="Completa sesiones para generar recomendaciones explicables." icon="fa-lightbulb"/></section></div>
    <div v-else-if="tab==='body'"><section class="grid stats-grid mb-3"><article class="stat-card"><strong>{{ body.summary.initial_weight??'-' }}</strong><small>Peso inicial (kg)</small></article><article class="stat-card"><strong>{{ body.summary.current_weight??'-' }}</strong><small>Peso actual (kg)</small></article><article class="stat-card"><strong>{{ change(body.summary.current_weight,body.summary.initial_weight) }}</strong><small>Cambio de peso (kg)</small></article><article class="stat-card"><strong>{{ trend('body_weight_kg') }}</strong><small>Tendencia de peso</small></article><article class="stat-card"><strong>{{ body.summary.initial_waist??'-' }}</strong><small>Cintura inicial (cm)</small></article><article class="stat-card"><strong>{{ body.summary.current_waist??'-' }}</strong><small>Cintura actual (cm)</small></article><article class="stat-card"><strong>{{ change(body.summary.current_waist,body.summary.initial_waist) }}</strong><small>Cambio de cintura (cm)</small></article><article class="stat-card"><strong>{{ trend('waist_cm') }}</strong><small>Tendencia de cintura</small></article></section><div class="grid two-column"><section class="surface panel"><div class="section-heading"><div><h2>Peso y cintura</h2><p>El peso no es la unica senal de exito.</p></div></div><LineChart :labels="bodyLabels" :datasets="bodyDatasets"/></section><section class="surface panel"><div class="section-heading"><h2>Mediciones</h2></div><div v-if="body.data.length" class="measurement-list"><div v-for="item in [...body.data].reverse()" :key="item.id" class="measurement-row"><div><strong>{{ new Date(`${item.recorded_on}T12:00:00`).toLocaleDateString('es-GT') }}</strong><small v-if="item.notes" class="d-block text-secondary">{{ item.notes }}</small></div><span>{{ item.body_weight_kg??'-' }} kg · {{ item.waist_cm??'-' }} cm</span><div class="d-flex gap-1"><button class="icon-button compact" title="Editar" @click="openMeasurement(item)"><i class="fa-solid fa-pen"/></button><button class="icon-button compact" title="Eliminar" @click="removeMeasurement(item)"><i class="fa-solid fa-trash"/></button></div></div></div><EmptyState v-else title="Sin linea base" text="Registra peso, cintura o ambos para iniciar la grafica." icon="fa-ruler"/></section></div></div>
    <div v-else-if="tab==='exercise'"><div class="surface panel mb-3"><label class="form-label">Ejercicio</label><select v-model="selectedExercise" class="form-select" @change="loadExercise"><option v-for="item in exercises" :key="item.id" :value="item.id">{{ item.name }}</option></select></div><template v-if="exerciseData"><section class="grid stats-grid mb-3"><article class="stat-card"><strong>{{ exerciseData.series.at(-1)?.max_weight||0 }}</strong><small>Peso maximo</small></article><article class="stat-card"><strong>{{ exerciseData.series.at(-1)?.total_repetitions||0 }}</strong><small>Reps totales</small></article><article class="stat-card"><strong>{{ Number(exerciseData.series.at(-1)?.volume||0).toFixed(0) }}</strong><small>Volumen</small></article><article class="stat-card"><strong>{{ Number(exerciseData.series.at(-1)?.estimated_one_rep_max||0).toFixed(1) }}</strong><small>1RM estimado</small></article><article class="stat-card"><strong>{{ exerciseData.series.at(-1)?.average_rir?.toFixed(1)??'-' }}</strong><small>RIR promedio</small></article><article class="stat-card"><strong>{{ exerciseData.calibration.complete?'Activo':'Calibrando' }}</strong><small>{{ exerciseData.calibration.exposures }} exposiciones</small></article><article class="stat-card"><strong>{{ exerciseData.series.at(-1)?.date?new Date(`${exerciseData.series.at(-1).date}T12:00:00`).toLocaleDateString('es-GT'):'-' }}</strong><small>Ultima sesion</small></article><article class="stat-card"><strong>{{ exerciseData.series.at(-1)?.best_set?`${exerciseData.series.at(-1).best_set.weight} x ${exerciseData.series.at(-1).best_set.repetitions}`:'-' }}</strong><small>Mejor serie</small></article><article class="stat-card"><strong>{{ exerciseData.recommendation?.recommendation_type==='possible_deload'?'Detectado':'Sin senal' }}</strong><small>Posible estancamiento</small></article></section><section v-if="exerciseData.recommendation" class="recommendation-row mb-3"><span class="badge-soft blue">{{ confidenceLabel(exerciseData.recommendation.confidence) }}</span><strong class="d-block mt-2">{{ recommendationLabel(exerciseData.recommendation.recommendation_type) }}</strong><p class="small text-secondary mb-0 mt-1">{{ exerciseData.recommendation.reason }}</p></section><section class="surface panel"><LineChart :labels="exerciseLabels" :datasets="exerciseDatasets" empty-text="Completa dos exposiciones para ver la tendencia."/></section><p class="small text-secondary mt-3">El volumen es una referencia util dentro del mismo ejercicio, pero no siempre es comparable entre maquinas o movimientos distintos.</p></template></div>
    <div v-else-if="tab==='achievements'"><div class="grid achievement-grid"><article v-for="item in achievements" :key="item.id" class="stat-card" :class="{locked:!item.unlocked_at}"><span class="stat-icon"><i class="fa-solid" :class="item.icon"/></span><strong style="font-size:16px">{{ item.name }}</strong><small>{{ item.description }}</small><span class="badge-soft mt-3" :class="item.unlocked_at?'green':''">{{ item.unlocked_at?'Desbloqueado':`${item.xp_reward} XP` }}</span></article></div></div>
  </template>
  <BaseModal :open="measurementOpen" :title="editingMeasurement?'Editar medicion':'Nueva medicion'" @close="measurementOpen=false"><form id="measurement-form" class="field-grid" @submit.prevent="saveMeasurement"><div class="grid-column-full"><label class="form-label">Fecha</label><input v-model="measurement.recorded_on" class="form-control" type="date" required/></div><div><label class="form-label">Peso (kg)</label><input v-model.number="measurement.body_weight_kg" class="form-control" type="number" min="20" max="500" step=".01" placeholder="Opcional"/></div><div><label class="form-label">Cintura (cm)</label><input v-model.number="measurement.waist_cm" class="form-control" type="number" min="30" max="300" step=".1" placeholder="Opcional"/></div><div class="grid-column-full"><label class="form-label">Notas</label><textarea v-model="measurement.notes" class="form-control" rows="3"/></div></form><template #footer><button class="btn btn-outline-light" @click="measurementOpen=false">Cancelar</button><button form="measurement-form" class="btn btn-primary"><i class="fa-solid fa-floppy-disk"/>Guardar</button></template></BaseModal>
  <BaseModal :open="recommendationOpen" title="Modificar recomendacion" @close="recommendationOpen=false"><form id="recommendation-form" class="field-grid" @submit.prevent="modifyRecommendation"><div><label class="form-label">Peso objetivo ({{ editingRecommendation?.weight_unit||'kg' }})</label><input v-model.number="recommendationChange.suggested_weight" class="form-control" type="number" min="0" max="2000" step=".01" placeholder="Opcional"/></div><div><label class="form-label">Repeticiones totales para la proxima sesion</label><input v-model.number="recommendationChange.suggested_total_repetitions" class="form-control" type="number" min="0" max="5000" placeholder="Opcional"/></div><p class="grid-column-full small text-secondary mb-0">La decision manual actualiza la meta de la rutina y queda registrada en el historial de recomendaciones.</p></form><template #footer><button class="btn btn-outline-light" @click="recommendationOpen=false">Cancelar</button><button form="recommendation-form" class="btn btn-primary"><i class="fa-solid fa-check"/>Aplicar cambio</button></template></BaseModal>
</div></template>
