<script setup>
import { computed, nextTick, onBeforeUnmount, onMounted, reactive, ref } from 'vue';
import { useRoute, useRouter } from 'vue-router';
import api from '../api/client';
import BaseModal from '../components/common/BaseModal.vue';
import EmptyState from '../components/common/EmptyState.vue';
import ExerciseDetailModal from '../components/exercises/ExerciseDetailModal.vue';
import LoadingSkeleton from '../components/common/LoadingSkeleton.vue';
import RestTimer from '../components/workout/RestTimer.vue';
import WorkoutSetRow from '../components/workout/WorkoutSetRow.vue';
import { useNotificationStore } from '../stores/notifications';
import { useWorkoutStore } from '../stores/workout';
import { errorMessage } from '../utils/errors';

const store=useWorkoutStore(); const notifications=useNotificationStore(); const route=useRoute(); const router=useRouter();
const routine=ref(null); const loading=ref(true); const checkInOpen=ref(false); const finishOpen=ref(false); const alternativeOpen=ref(false); const detailOpen=ref(false); const selectedDay=ref(null); const timer=ref(null); const quickMode=ref(false); const elapsedSeconds=ref(0); let elapsedTicker=null;
const checkIn=reactive({routine_day_id:null,sleep_hours:null,energy_level:null,motivation_level:null,discomfort_notes:null}); const feedback=reactive({session_difficulty:null,session_satisfaction:null,is_atypical:false,atypical_reason:null,notes:null});
const current=computed(()=>store.currentExercise); const planned=computed(()=>current.value?.planned||{}); const exercise=computed(()=>current.value?.performed_exercise||{});
const visibleExercises=computed(()=>store.session?.exercises?.filter(item=>!quickMode.value||item.planned?.priority!=='optional')||[]);
const newSetNumber=computed(()=>Math.max(0,...(current.value?.sets||[]).map(set=>set.set_number))+1);
const completedSets=computed(()=>store.session?.exercises?.flatMap(item=>item.sets||[]).filter(set=>set.completed&&set.set_type!=='warmup')||[]);
const hasNextVisible=computed(()=>store.session?.exercises?.slice(store.currentIndex+1).some(item=>!quickMode.value||item.planned?.priority!=='optional'));
const plannedSetCount=computed(()=>visibleExercises.value.reduce((sum,item)=>sum+(item.planned?.target_sets||0),0));
const volume=computed(()=>completedSets.value.reduce((sum,set)=>sum+Number(set.volume||0),0));
const visibleIndex=computed(()=>Math.max(0,visibleExercises.value.findIndex(item=>item.id===current.value?.id)));
const completedExerciseCount=computed(()=>visibleExercises.value.filter(item=>(item.sets||[]).some(set=>set.completed&&set.set_type!=='warmup')).length);
const pendingExerciseCount=computed(()=>Math.max(0,visibleExercises.value.length-completedExerciseCount.value));
const preliminaryRecords=computed(()=>completedSets.value.filter(set=>set.is_personal_record).length);
const elapsedLabel=computed(()=>`${String(Math.floor(elapsedSeconds.value/60)).padStart(2,'0')}:${String(elapsedSeconds.value%60).padStart(2,'0')}`);
async function initialize(){ try { await store.restore(); if(!store.session){routine.value=(await api.get('/routine')).data.data; const day=routine.value.days.find(item=>item.id===Number(route.query.day)); if(day)openCheckIn(day);} } catch(e){notifications.push(errorMessage(e),'error');} finally{loading.value=false;} }
function openCheckIn(day){selectedDay.value=day; checkIn.routine_day_id=day.id; checkInOpen.value=true;}
async function start(){try{await store.start(checkIn);checkInOpen.value=false;}catch(e){notifications.push(errorMessage(e),'error');}}
async function saveSet(payload,set=null){try{const result=set?await store.updateSet(set.id,payload):await store.addSet(current.value.id,payload); if(result.new_records?.length)notifications.push('Nuevo record personal.');else notifications.push('Serie guardada.'); if(payload.set_type!=='warmup'){await nextTick();timer.value?.start(planned.value.rest_seconds||90);}}catch(e){notifications.push(errorMessage(e),'error');}}
async function removeSet(id){if(!confirm('Eliminar esta serie?'))return;try{await store.deleteSet(id);notifications.push('Serie eliminada.');}catch(e){notifications.push(errorMessage(e),'error');}}
function copyPrevious(){const last=current.value.previous_performance?.sets?.filter(set=>set.set_type==='working').at(-1); if(!last){notifications.push('No hay una serie anterior para copiar.','error');return;} saveSet({...last,id:undefined,set_number:newSetNumber.value,completed:true,completed_at:undefined});}
async function substitute(alternative){try{await store.substitute(current.value.id,{alternative_exercise_id:alternative.id,reason:alternative.reason||'equipment_busy'});alternativeOpen.value=false;notifications.push('Alternativa cargada con su historial independiente.');}catch(e){notifications.push(errorMessage(e),'error');}}
async function finish(status){try{const result=await store.finish(status,feedback);finishOpen.value=false;notifications.push(status==='partial'?'Entrenamiento guardado como parcial.':`Entrenamiento completado: +${result.xp_earned} XP`);router.push({name:'history-detail',params:{id:result.id}});}catch(e){notifications.push(errorMessage(e),'error');}}
async function cancel(){if(!confirm('Cancelar el entrenamiento? Las series registradas permaneceran en el historial.'))return;try{await store.cancel();notifications.push('Entrenamiento cancelado.');await initialize();}catch(e){notifications.push(errorMessage(e),'error');}}
function jump(direction){do{store[direction]();}while(quickMode.value&&current.value?.planned?.priority==='optional'&&((direction==='next'&&store.currentIndex<store.exerciseCount-1)||(direction==='previous'&&store.currentIndex>0)));window.scrollTo({top:0,behavior:'smooth'});}
function applyQuickMode(){if(quickMode.value&&current.value?.planned?.priority==='optional')jump(hasNextVisible.value?'next':'previous');}
const confidenceLabels={low:'Baja',medium:'Media',high:'Alta'};
const confidenceLabel=value=>confidenceLabels[value]||value;
function updateElapsed(){elapsedSeconds.value=store.session?.started_at?Math.max(0,Math.floor((Date.now()-new Date(store.session.started_at).getTime())/1000)):0;}
onMounted(()=>{initialize();updateElapsed();elapsedTicker=setInterval(updateElapsed,1000);});
onBeforeUnmount(()=>clearInterval(elapsedTicker));
</script>
<template>
  <div class="workout-shell">
    <LoadingSkeleton v-if="loading"/>
    <template v-else-if="!store.session">
      <header class="page-header"><div><div class="eyebrow">Entrenamiento</div><h1>Elige una sesion</h1><p>Puedes recuperar una sesion aunque no corresponda al dia de hoy.</p></div></header>
      <div v-if="routine" class="day-list"><article v-for="day in routine.days.filter(item=>item.day_type==='training')" :key="day.id" class="day-card"><header><div><h3>{{ day.name }}</h3><small>{{ day.exercises.length }} ejercicios · {{ day.estimated_minutes }} min</small></div><button class="btn btn-primary" @click="openCheckIn(day)"><i class="fa-solid fa-play"/>Iniciar</button></header></article></div>
      <EmptyState v-else title="No hay rutina activa" text="Configura al menos un dia de entrenamiento antes de iniciar." icon="fa-list-check"/>
    </template>
    <template v-else-if="current">
      <div class="workout-top"><div class="workout-counter"><span>{{ store.session.name }}<small class="d-block text-secondary"><i class="fa-solid fa-stopwatch me-1"/>{{ elapsedLabel }} · {{ Math.round((store.session.routine_snapshot?.day?.estimated_minutes||75)*(quickMode ? 0.78 : 1)) }} min est.</small></span><span>{{ visibleIndex+1 }} de {{ visibleExercises.length }}</span></div><div class="d-flex align-items-center gap-2 mb-2"><div class="progress-track flex-grow-1"><span :style="{width:`${(visibleIndex+1)/Math.max(1,visibleExercises.length)*100}%`}"/></div><label class="badge-soft" :class="{green:quickMode}"><input v-model="quickMode" class="form-check-input m-0" type="checkbox" @change="applyQuickMode"/>Rapido</label></div></div>
      <section class="surface workout-exercise">
        <header class="workout-exercise-header"><div class="d-flex justify-content-between gap-3"><div><span v-if="current.was_substituted" class="badge-soft yellow"><i class="fa-solid fa-shuffle"/>Alternativa</span><h1>{{ exercise.name }}</h1><small class="text-secondary d-block mb-2">{{ exercise.muscle_groups?.map(group=>group.name).join(', ')||'Grupo muscular sin especificar' }}</small><div class="workout-meta"><span class="badge-soft">{{ planned.target_sets }} x {{ planned.minimum_reps }}-{{ planned.maximum_reps }}</span><span class="badge-soft blue">RIR {{ planned.target_rir_min }}-{{ planned.target_rir_max }}</span><span class="badge-soft"><i class="fa-solid fa-stopwatch"/>{{ planned.rest_seconds }} s</span><span class="badge-soft green">{{ planned.target_weight===null?'Por calibrar':`${planned.target_weight} ${planned.weight_unit}` }}</span></div></div><div class="d-flex align-items-center gap-2 flex-shrink-0"><button class="icon-button compact" :title="`Ver detalles de ${exercise.name}`" @click="detailOpen=true"><i class="fa-solid fa-eye"/></button><div class="exercise-thumb"><img v-if="exercise.image_url" :src="exercise.image_url" :alt="exercise.name" class="w-100 h-100 object-fit-cover rounded"/><i v-else class="fa-solid fa-dumbbell"/></div></div></div><p v-if="planned.notes" class="small text-secondary mt-3 mb-0"><i class="fa-solid fa-note-sticky me-2"/>{{ planned.notes }}</p><p v-if="store.currentIndex===0" class="small text-secondary mt-3 mb-0"><i class="fa-solid fa-person-running me-2"/>Realiza de 5 a 8 minutos de calentamiento general y varias series progresivas ligeras antes del primer movimiento pesado.</p></header>
        <div class="workout-context"><div class="context-panel"><h3>Ultima vez</h3><template v-if="current.previous_performance"><p>{{ new Date(current.previous_performance.date).toLocaleDateString('es-GT') }}</p><p class="text-secondary mt-1">{{ current.previous_performance.sets.filter(s=>s.set_type==='working').map(s=>`${s.weight ?? '-'} ${s.weight_unit ?? ''} x ${s.repetitions ?? s.duration_seconds}`).join(' · ') }}</p></template><p v-else class="text-secondary">Sin exposiciones anteriores.</p></div><div class="context-panel recommendation-accent"><h3>Objetivo de hoy · {{ confidenceLabel(current.recommendation?.confidence) }}</h3><p>{{ current.recommendation?.reason }}</p></div></div>
        <div class="p-3"><div class="d-flex align-items-center justify-content-between mb-2"><strong>Series</strong><div class="d-flex gap-1"><button class="icon-button compact" title="Copiar serie anterior" @click="copyPrevious"><i class="fa-solid fa-copy"/></button><button class="icon-button compact" title="Usar alternativa" :disabled="current.sets.length>0" @click="alternativeOpen=true"><i class="fa-solid fa-shuffle"/></button></div></div><div class="table-responsive"><table class="sets-table"><thead><tr><th>#</th><th>Tipo</th><th v-if="exercise.metric_type!=='duration'&&exercise.metric_type!=='reps_only'&&exercise.metric_type!=='bodyweight_reps'">Peso</th><th>{{ exercise.metric_type?.includes('duration')?'Seg':'Reps' }}</th><th>RIR</th><th></th><th></th></tr></thead><tbody><WorkoutSetRow v-for="set in current.sets" :key="set.id" :set="set" :number="set.set_number" :unit="exercise.default_weight_unit" :metric-type="exercise.metric_type" @save="saveSet($event,set)" @remove="removeSet"/><WorkoutSetRow :key="`new-${current.id}-${newSetNumber}`" :number="newSetNumber" :unit="exercise.default_weight_unit" :metric-type="exercise.metric_type" @save="saveSet"/></tbody></table></div></div>
        <RestTimer ref="timer" :default-seconds="planned.rest_seconds||90"/>
      </section>
      <div class="workout-actions"><button class="btn btn-outline-light" :disabled="store.currentIndex===0" @click="jump('previous')"><i class="fa-solid fa-arrow-left"/>Anterior</button><button v-if="hasNextVisible" class="btn btn-primary" @click="jump('next')">Siguiente<i class="fa-solid fa-arrow-right"/></button><button v-else class="btn btn-primary" @click="finishOpen=true"><i class="fa-solid fa-flag-checkered"/>Finalizar</button></div>
      <div class="d-flex justify-content-center mt-3"><button class="btn btn-danger-soft" @click="cancel"><i class="fa-solid fa-xmark"/>Cancelar sesion</button></div>
    </template>

    <ExerciseDetailModal :open="detailOpen" :exercise="exercise" @close="detailOpen=false"/>
    <BaseModal :open="checkInOpen" :title="`Iniciar ${selectedDay?.name || 'entrenamiento'}`" @close="checkInOpen=false"><form id="checkin-form" class="field-grid" @submit.prevent="start"><div><label class="form-label">Horas de sueno</label><input v-model.number="checkIn.sleep_hours" class="form-control" type="number" min="0" max="24" step=".5" placeholder="Opcional"/></div><div><label class="form-label">Energia (1-5)</label><input v-model.number="checkIn.energy_level" class="form-control" type="number" min="1" max="5" placeholder="Opcional"/></div><div><label class="form-label">Motivacion (1-5)</label><input v-model.number="checkIn.motivation_level" class="form-control" type="number" min="1" max="5" placeholder="Opcional"/></div><div class="grid-column-full"><label class="form-label">Molestias o comentarios</label><textarea v-model="checkIn.discomfort_notes" class="form-control" rows="3" placeholder="Opcional"/></div></form><template #footer><button class="btn btn-outline-light" @click="checkInOpen=false">Cancelar</button><button form="checkin-form" class="btn btn-primary"><i class="fa-solid fa-play"/>Comenzar</button></template></BaseModal>
    <BaseModal :open="alternativeOpen" title="Usar alternativa" @close="alternativeOpen=false"><div v-if="current?.planned_exercise?.alternatives?.length" class="exercise-list"><article v-for="alternative in current.planned_exercise.alternatives" :key="alternative.id" class="exercise-row"><div class="exercise-thumb"><i class="fa-solid fa-shuffle"/></div><div class="exercise-info"><h3>{{ alternative.name }}</h3><select v-model="alternative.reason" class="form-select mt-2"><option value="equipment_busy">Equipo ocupado</option><option value="equipment_unavailable">Equipo no disponible</option><option value="discomfort">Molestia</option><option value="personal_preference">Preferencia personal</option><option value="other">Otro</option></select></div><button class="btn btn-primary" @click="substitute(alternative)">Usar</button></article></div><EmptyState v-else title="Sin alternativas configuradas" text="Agrega alternativas desde la biblioteca de ejercicios." icon="fa-shuffle"/></BaseModal>
    <BaseModal :open="finishOpen" title="Finalizar entrenamiento" @close="finishOpen=false"><div class="grid stats-grid mb-4"><article class="stat-card"><strong>{{ completedExerciseCount }}</strong><small>Ejercicios completados</small></article><article class="stat-card"><strong>{{ pendingExerciseCount }}</strong><small>Ejercicios pendientes</small></article><article class="stat-card"><strong>{{ completedSets.length }}/{{ plannedSetCount }}</strong><small>Series efectivas</small></article><article class="stat-card"><strong>{{ elapsedLabel }}</strong><small>Duracion</small></article><article class="stat-card"><strong>{{ volume.toFixed(0) }}</strong><small>Volumen</small></article><article class="stat-card"><strong>{{ preliminaryRecords }}</strong><small>Records preliminares</small></article></div><form class="field-grid"><div><label class="form-label">Dificultad (1-5)</label><input v-model.number="feedback.session_difficulty" class="form-control" type="number" min="1" max="5"/></div><div><label class="form-label">Satisfaccion (1-5)</label><input v-model.number="feedback.session_satisfaction" class="form-control" type="number" min="1" max="5"/></div><div class="grid-column-full form-check"><input id="atypical" v-model="feedback.is_atypical" class="form-check-input" type="checkbox"/><label for="atypical" class="form-check-label">Esta sesion fue atipica</label></div><div v-if="feedback.is_atypical" class="grid-column-full"><label class="form-label">Motivo</label><input v-model="feedback.atypical_reason" class="form-control" placeholder="Poco sueno, equipo distinto, interrupciones..."/></div><div class="grid-column-full"><label class="form-label">Notas finales</label><textarea v-model="feedback.notes" class="form-control" rows="3"/></div></form><template #footer><button class="btn btn-outline-light me-auto" @click="finishOpen=false">Continuar entrenando</button><button class="btn btn-outline-light" @click="finish('partial')">Guardar parcial</button><button class="btn btn-primary" @click="finish('completed')"><i class="fa-solid fa-check"/>Completar</button></template></BaseModal>
  </div>
</template>
