<script setup>
import { computed, onBeforeUnmount, onMounted, reactive, ref } from 'vue';
import api from '../../api/client';
import BaseModal from '../common/BaseModal.vue';
import EmptyState from '../common/EmptyState.vue';
import { useNotificationStore } from '../../stores/notifications';
import { errorMessage } from '../../utils/errors';
const emit=defineEmits(['changed']); const notifications=useNotificationStore();
const exercises=ref([]); const groups=ref([]); const search=ref(''); const muscleFilter=ref(''); const equipmentFilter=ref(''); const selected=ref(null); const open=ref(false); const image=ref(null); const imagePreview=ref(null); const alternativeId=ref(null);
const form=reactive({name:'',description:'',instructions:'',equipment:'',youtube_url:'',metric_type:'weight_reps',weight_mode:'machine_stack',default_weight_unit:'kg',default_increment:2.5,is_active:true,muscle_group_ids:[]});
const equipmentOptions=computed(()=>[...new Set(exercises.value.map(item=>item.equipment).filter(Boolean))].sort());
const filtered=computed(()=>exercises.value.filter(item=>item.name.toLowerCase().includes(search.value.toLowerCase())&&(!muscleFilter.value||item.muscle_groups?.some(group=>group.slug===muscleFilter.value))&&(!equipmentFilter.value||item.equipment===equipmentFilter.value)));
async function load(){ const response=await api.get('/exercises',{params:{include_inactive:true,per_page:100}}); exercises.value=response.data.data; groups.value=[...new Map(exercises.value.flatMap(x=>x.muscle_groups||[]).map(x=>[x.id,x])).values()]; }
function resetImage(){if(imagePreview.value)URL.revokeObjectURL(imagePreview.value);image.value=null;imagePreview.value=null;}
function chooseImage(event){resetImage();image.value=event.target.files?.[0]||null;if(image.value)imagePreview.value=URL.createObjectURL(image.value);}
function edit(item=null){ resetImage(); selected.value=item; Object.assign(form,item?{name:item.name,description:item.description||'',instructions:item.instructions||'',equipment:item.equipment||'',youtube_url:item.youtube_url||'',metric_type:item.metric_type,weight_mode:item.weight_mode,default_weight_unit:item.default_weight_unit,default_increment:item.default_increment,is_active:item.is_active,muscle_group_ids:(item.muscle_groups||[]).map(g=>g.id)}:{name:'',description:'',instructions:'',equipment:'',youtube_url:'',metric_type:'weight_reps',weight_mode:'machine_stack',default_weight_unit:'kg',default_increment:2.5,is_active:true,muscle_group_ids:[]}); open.value=true; }
async function save(){ try { let item; if(selected.value) item=(await api.put(`/exercises/${selected.value.id}`,form)).data.data; else item=(await api.post('/exercises',form)).data.data; if(image.value){ const payload=new FormData(); payload.append('image',image.value); item=(await api.post(`/exercises/${item.id}/image`,payload)).data.data; } notifications.push('Ejercicio guardado.'); open.value=false; resetImage(); await load(); emit('changed'); } catch(e){ notifications.push(errorMessage(e),'error'); } }
async function deactivate(item){ try { await api.delete(`/exercises/${item.id}`); notifications.push('Ejercicio desactivado.'); await load(); emit('changed'); } catch(e){ notifications.push(errorMessage(e),'error'); } }
async function addAlternative(){ if(!selected.value||!alternativeId.value)return; try{await api.post(`/exercises/${selected.value.id}/alternatives`,{alternative_exercise_id:alternativeId.value});notifications.push('Alternativa agregada.');await load();selected.value=exercises.value.find(item=>item.id===selected.value.id);alternativeId.value=null;}catch(e){notifications.push(errorMessage(e),'error');} }
async function removeAlternative(item){try{await api.delete(`/exercise-alternatives/${item.alternative_relation_id}`);notifications.push('Alternativa eliminada.');await load();selected.value=exercises.value.find(current=>current.id===selected.value.id);}catch(e){notifications.push(errorMessage(e),'error');}}
async function moveAlternative(index,direction){const next=index+direction;if(next<0||next>=selected.value.alternatives.length)return;const items=[...selected.value.alternatives];[items[index],items[next]]=[items[next],items[index]];try{await api.post('/exercise-alternatives/reorder',{exercise_id:selected.value.id,ids:items.map(item=>item.alternative_relation_id)});await load();selected.value=exercises.value.find(current=>current.id===selected.value.id);}catch(e){notifications.push(errorMessage(e),'error');}}
onBeforeUnmount(resetImage);
async function deleteImage(){if(!selected.value?.image_url||!confirm('Eliminar la imagen de este ejercicio?'))return;try{await api.delete(`/exercises/${selected.value.id}/image`);notifications.push('Imagen eliminada.');await load();selected.value=exercises.value.find(current=>current.id===selected.value.id);}catch(e){notifications.push(errorMessage(e),'error');}}
onMounted(load);
</script>
<template>
  <div>
    <div class="grid filter-grid mb-3"><div class="input-group"><span class="input-group-text"><i class="fa-solid fa-magnifying-glass"/></span><input v-model="search" class="form-control" placeholder="Buscar por nombre"/></div><select v-model="muscleFilter" class="form-select"><option value="">Todos los musculos</option><option v-for="group in groups" :key="group.id" :value="group.slug">{{ group.name }}</option></select><select v-model="equipmentFilter" class="form-select"><option value="">Todo el equipo</option><option v-for="item in equipmentOptions" :key="item">{{ item }}</option></select><button class="btn btn-primary" title="Crear ejercicio" @click="edit()"><i class="fa-solid fa-plus"/><span>Crear</span></button></div>
    <div v-if="filtered.length" class="exercise-list"><article v-for="item in filtered" :key="item.id" class="exercise-row"><div class="exercise-thumb"><img v-if="item.image_url" :src="item.image_url" :alt="item.name" class="w-100 h-100 rounded object-fit-cover"/><i v-else class="fa-solid fa-dumbbell"/></div><div class="exercise-info"><h3>{{ item.name }}</h3><small>{{ item.equipment || 'Sin equipo' }} · {{ item.muscle_groups?.map(g=>g.name).join(', ') || 'Sin grupo' }}</small><div class="mt-1"><span v-if="!item.is_active" class="badge-soft red">Inactivo</span><span v-if="item.alternatives?.length" class="badge-soft blue">{{ item.alternatives.length }} alternativas</span></div></div><button class="icon-button compact" title="Editar" @click="edit(item)"><i class="fa-solid fa-pen"/></button><button class="icon-button compact" title="Desactivar" :disabled="!item.is_active" @click="deactivate(item)"><i class="fa-solid fa-trash"/></button></article></div>
    <EmptyState v-else title="No hay ejercicios" text="Cambia la busqueda o crea un ejercicio personal." icon="fa-dumbbell"/>
    <BaseModal :open="open" :title="selected?'Editar ejercicio':'Nuevo ejercicio'" size="wide" @close="open=false">
      <form id="exercise-form" class="field-grid" @submit.prevent="save">
        <div><label class="form-label">Nombre</label><input v-model="form.name" class="form-control" required maxlength="120"/></div><div><label class="form-label">Equipo</label><input v-model="form.equipment" class="form-control" maxlength="100"/></div>
        <div><label class="form-label">Tipo de metrica</label><select v-model="form.metric_type" class="form-select"><option value="weight_reps">Peso y repeticiones</option><option value="reps_only">Solo repeticiones</option><option value="duration">Duracion</option><option value="weight_duration">Peso y duracion</option><option value="bodyweight_reps">Peso corporal</option><option value="bodyweight_added_weight">Peso corporal + carga</option></select></div>
        <div><label class="form-label">Modo de peso</label><select v-model="form.weight_mode" class="form-select"><option value="total">Total</option><option value="per_dumbbell">Por mancuerna</option><option value="per_side">Por lado</option><option value="machine_stack">Pila de maquina</option><option value="added_weight">Peso anadido</option><option value="bodyweight">Peso corporal</option><option value="not_applicable">No aplica</option></select></div>
        <div><label class="form-label">Unidad</label><select v-model="form.default_weight_unit" class="form-select"><option value="kg">kg</option><option value="lb">lb</option></select></div><div><label class="form-label">Incremento</label><input v-model.number="form.default_increment" class="form-control" type="number" min=".01" step=".01"/></div>
        <div class="grid-column-full"><label class="form-label">Descripcion</label><textarea v-model="form.description" class="form-control" rows="2"/></div><div class="grid-column-full"><label class="form-label">Instrucciones</label><textarea v-model="form.instructions" class="form-control" rows="3"/></div>
        <div class="grid-column-full"><label class="form-label" for="exercise-youtube-url">Video de referencia de YouTube</label><input id="exercise-youtube-url" v-model.trim="form.youtube_url" class="form-control" type="url" maxlength="2048" placeholder="https://www.youtube.com/watch?v=..."/></div>
        <div class="grid-column-full"><label class="form-label">Imagen (jpg, png o webp; maximo 4 MB)</label><div v-if="imagePreview||selected?.image_url" class="exercise-image-preview mb-2"><img :src="imagePreview||selected.image_url" :alt="`Vista previa de ${form.name}`"/></div><div class="d-flex gap-2"><input class="form-control" type="file" accept="image/jpeg,image/png,image/webp" @change="chooseImage"/><button v-if="selected?.image_url&&!imagePreview" type="button" class="btn btn-danger-soft" title="Eliminar imagen" @click="deleteImage"><i class="fa-solid fa-trash"/></button></div></div>
        <div v-if="selected" class="grid-column-full alternative-editor"><label class="form-label">Alternativas ordenadas</label><div class="d-flex gap-2"><select v-model.number="alternativeId" class="form-select"><option :value="null">Selecciona un ejercicio</option><option v-for="item in exercises.filter(item=>item.id!==selected.id&&!selected.alternatives?.some(alt=>alt.id===item.id))" :key="item.id" :value="item.id">{{ item.name }}</option></select><button type="button" class="btn btn-outline-light" :disabled="!alternativeId" @click="addAlternative"><i class="fa-solid fa-plus"/>Agregar</button></div><div class="planned-exercises"><div v-for="(item,index) in selected.alternatives" :key="item.id" class="planned-item"><span class="position">{{ index+1 }}</span><strong>{{ item.name }}</strong><div class="d-flex gap-1"><button type="button" class="icon-button compact" title="Subir" :disabled="index===0" @click="moveAlternative(index,-1)"><i class="fa-solid fa-arrow-up"/></button><button type="button" class="icon-button compact" title="Bajar" :disabled="index===selected.alternatives.length-1" @click="moveAlternative(index,1)"><i class="fa-solid fa-arrow-down"/></button><button type="button" class="icon-button compact" title="Eliminar alternativa" @click="removeAlternative(item)"><i class="fa-solid fa-trash"/></button></div></div><small v-if="!selected.alternatives?.length" class="text-secondary">No hay alternativas configuradas.</small></div></div>
      </form>
      <template #footer><RouterLink v-if="selected" class="btn btn-outline-light me-auto" :to="{name:'progress',query:{exercise:selected.id}}" @click="open=false"><i class="fa-solid fa-chart-line"/>Ver historial</RouterLink><button class="btn btn-outline-light" @click="open=false">Cancelar</button><button form="exercise-form" class="btn btn-primary"><i class="fa-solid fa-floppy-disk"/>Guardar</button></template>
    </BaseModal>
  </div>
</template>
